// This file is generated by raylib-raku
#include <raylib.h>
#include <stdlib.h>
void SetWindowIcon_pointerized(Image* image){ SetWindowIcon(*image); }
Vector2* GetMonitorPosition_pointerized(int monitor){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetMonitorPosition(monitor); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetWindowPosition_pointerized(){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetWindowPosition(); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetWindowScaleDPI_pointerized(){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetWindowScaleDPI(); 
    *ptr = ret; 
    return ptr;
}
void ClearBackground_pointerized(Color* color){ ClearBackground(*color); }
void BeginMode2D_pointerized(Camera2D* camera){ BeginMode2D(*camera); }
void BeginMode3D_pointerized(Camera3D* camera){ BeginMode3D(*camera); }
void BeginTextureMode_pointerized(RenderTexture2D* target){ BeginTextureMode(*target); }
void BeginShaderMode_pointerized(Shader* shader){ BeginShaderMode(*shader); }
void BeginVrStereoMode_pointerized(VrStereoConfig* config){ BeginVrStereoMode(*config); }
VrStereoConfig* LoadVrStereoConfig_pointerized(VrDeviceInfo* device){
    VrStereoConfig* ptr = malloc(sizeof(VrStereoConfig));
    VrStereoConfig ret = LoadVrStereoConfig(*device); 
    *ptr = ret; 
    return ptr;
}
void UnloadVrStereoConfig_pointerized(VrStereoConfig* config){ UnloadVrStereoConfig(*config); }
Shader* LoadShader_pointerized( char * vsFileName,  char * fsFileName){
    Shader* ptr = malloc(sizeof(Shader));
    Shader ret = LoadShader(vsFileName, fsFileName); 
    *ptr = ret; 
    return ptr;
}
Shader* LoadShaderFromMemory_pointerized( char * vsCode,  char * fsCode){
    Shader* ptr = malloc(sizeof(Shader));
    Shader ret = LoadShaderFromMemory(vsCode, fsCode); 
    *ptr = ret; 
    return ptr;
}
bool IsShaderReady_pointerized(Shader* shader){ return IsShaderReady(*shader); }
int GetShaderLocation_pointerized(Shader* shader,  char * uniformName){ return GetShaderLocation(*shader, uniformName); }
int GetShaderLocationAttrib_pointerized(Shader* shader,  char * attribName){ return GetShaderLocationAttrib(*shader, attribName); }
void SetShaderValue_pointerized(Shader* shader, int locIndex,  void * value, int uniformType){ SetShaderValue(*shader, locIndex, value, uniformType); }
void SetShaderValueV_pointerized(Shader* shader, int locIndex,  void * value, int uniformType, int count){ SetShaderValueV(*shader, locIndex, value, uniformType, count); }
void SetShaderValueMatrix_pointerized(Shader* shader, int locIndex, Matrix* mat){ SetShaderValueMatrix(*shader, locIndex, *mat); }
void SetShaderValueTexture_pointerized(Shader* shader, int locIndex, Texture2D* texture){ SetShaderValueTexture(*shader, locIndex, *texture); }
void UnloadShader_pointerized(Shader* shader){ UnloadShader(*shader); }
Ray* GetMouseRay_pointerized(Vector2* mousePosition, Camera* camera){
    Ray* ptr = malloc(sizeof(Ray));
    Ray ret = GetMouseRay(*mousePosition, *camera); 
    *ptr = ret; 
    return ptr;
}
Matrix* GetCameraMatrix_pointerized(Camera* camera){
    Matrix* ptr = malloc(sizeof(Matrix));
    Matrix ret = GetCameraMatrix(*camera); 
    *ptr = ret; 
    return ptr;
}
Matrix* GetCameraMatrix2D_pointerized(Camera2D* camera){
    Matrix* ptr = malloc(sizeof(Matrix));
    Matrix ret = GetCameraMatrix2D(*camera); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetWorldToScreen_pointerized(Vector3* position, Camera* camera){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetWorldToScreen(*position, *camera); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetScreenToWorld2D_pointerized(Vector2* position, Camera2D* camera){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetScreenToWorld2D(*position, *camera); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetWorldToScreenEx_pointerized(Vector3* position, Camera* camera, int width, int height){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetWorldToScreenEx(*position, *camera, width, height); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetWorldToScreen2D_pointerized(Vector2* position, Camera2D* camera){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetWorldToScreen2D(*position, *camera); 
    *ptr = ret; 
    return ptr;
}
FilePathList* LoadDirectoryFiles_pointerized( char * dirPath){
    FilePathList* ptr = malloc(sizeof(FilePathList));
    FilePathList ret = LoadDirectoryFiles(dirPath); 
    *ptr = ret; 
    return ptr;
}
FilePathList* LoadDirectoryFilesEx_pointerized( char * basePath,  char * filter, bool scanSubdirs){
    FilePathList* ptr = malloc(sizeof(FilePathList));
    FilePathList ret = LoadDirectoryFilesEx(basePath, filter, scanSubdirs); 
    *ptr = ret; 
    return ptr;
}
void UnloadDirectoryFiles_pointerized(FilePathList* files){ UnloadDirectoryFiles(*files); }
FilePathList* LoadDroppedFiles_pointerized(){
    FilePathList* ptr = malloc(sizeof(FilePathList));
    FilePathList ret = LoadDroppedFiles(); 
    *ptr = ret; 
    return ptr;
}
void UnloadDroppedFiles_pointerized(FilePathList* files){ UnloadDroppedFiles(*files); }
long* GetFileModTime_pointerized( char * fileName){
    long* ptr = malloc(sizeof(long));
    long ret = GetFileModTime(fileName); 
    *ptr = ret; 
    return ptr;
}
AutomationEventList* LoadAutomationEventList_pointerized( char * fileName){
    AutomationEventList* ptr = malloc(sizeof(AutomationEventList));
    AutomationEventList ret = LoadAutomationEventList(fileName); 
    *ptr = ret; 
    return ptr;
}
bool ExportAutomationEventList_pointerized(AutomationEventList* list,  char * fileName){ return ExportAutomationEventList(*list, fileName); }
void PlayAutomationEvent_pointerized(AutomationEvent* event){ PlayAutomationEvent(*event); }
Vector2* GetMousePosition_pointerized(){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetMousePosition(); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetMouseDelta_pointerized(){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetMouseDelta(); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetMouseWheelMoveV_pointerized(){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetMouseWheelMoveV(); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetTouchPosition_pointerized(int index){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetTouchPosition(index); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetGestureDragVector_pointerized(){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetGestureDragVector(); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetGesturePinchVector_pointerized(){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetGesturePinchVector(); 
    *ptr = ret; 
    return ptr;
}
void UpdateCameraPro_pointerized( Camera * camera, Vector3* movement, Vector3* rotation, float zoom){ UpdateCameraPro(camera, *movement, *rotation, zoom); }
void SetShapesTexture_pointerized(Texture2D* texture, Rectangle* source){ SetShapesTexture(*texture, *source); }
void DrawPixel_pointerized(int posX, int posY, Color* color){ DrawPixel(posX, posY, *color); }
void DrawPixelV_pointerized(Vector2* position, Color* color){ DrawPixelV(*position, *color); }
void DrawLine_pointerized(int startPosX, int startPosY, int endPosX, int endPosY, Color* color){ DrawLine(startPosX, startPosY, endPosX, endPosY, *color); }
void DrawLineV_pointerized(Vector2* startPos, Vector2* endPos, Color* color){ DrawLineV(*startPos, *endPos, *color); }
void DrawLineEx_pointerized(Vector2* startPos, Vector2* endPos, float thick, Color* color){ DrawLineEx(*startPos, *endPos, thick, *color); }
void DrawLineStrip_pointerized( Vector2 * points, int pointCount, Color* color){ DrawLineStrip(points, pointCount, *color); }
void DrawLineBezier_pointerized(Vector2* startPos, Vector2* endPos, float thick, Color* color){ DrawLineBezier(*startPos, *endPos, thick, *color); }
void DrawCircle_pointerized(int centerX, int centerY, float radius, Color* color){ DrawCircle(centerX, centerY, radius, *color); }
void DrawCircleSector_pointerized(Vector2* center, float radius, float startAngle, float endAngle, int segments, Color* color){ DrawCircleSector(*center, radius, startAngle, endAngle, segments, *color); }
void DrawCircleSectorLines_pointerized(Vector2* center, float radius, float startAngle, float endAngle, int segments, Color* color){ DrawCircleSectorLines(*center, radius, startAngle, endAngle, segments, *color); }
void DrawCircleGradient_pointerized(int centerX, int centerY, float radius, Color* color1, Color* color2){ DrawCircleGradient(centerX, centerY, radius, *color1, *color2); }
void DrawCircleV_pointerized(Vector2* center, float radius, Color* color){ DrawCircleV(*center, radius, *color); }
void DrawCircleLines_pointerized(int centerX, int centerY, float radius, Color* color){ DrawCircleLines(centerX, centerY, radius, *color); }
void DrawCircleLinesV_pointerized(Vector2* center, float radius, Color* color){ DrawCircleLinesV(*center, radius, *color); }
void DrawEllipse_pointerized(int centerX, int centerY, float radiusH, float radiusV, Color* color){ DrawEllipse(centerX, centerY, radiusH, radiusV, *color); }
void DrawEllipseLines_pointerized(int centerX, int centerY, float radiusH, float radiusV, Color* color){ DrawEllipseLines(centerX, centerY, radiusH, radiusV, *color); }
void DrawRing_pointerized(Vector2* center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color* color){ DrawRing(*center, innerRadius, outerRadius, startAngle, endAngle, segments, *color); }
void DrawRingLines_pointerized(Vector2* center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color* color){ DrawRingLines(*center, innerRadius, outerRadius, startAngle, endAngle, segments, *color); }
void DrawRectangle_pointerized(int posX, int posY, int width, int height, Color* color){ DrawRectangle(posX, posY, width, height, *color); }
void DrawRectangleV_pointerized(Vector2* position, Vector2* size, Color* color){ DrawRectangleV(*position, *size, *color); }
void DrawRectangleRec_pointerized(Rectangle* rec, Color* color){ DrawRectangleRec(*rec, *color); }
void DrawRectanglePro_pointerized(Rectangle* rec, Vector2* origin, float rotation, Color* color){ DrawRectanglePro(*rec, *origin, rotation, *color); }
void DrawRectangleGradientV_pointerized(int posX, int posY, int width, int height, Color* color1, Color* color2){ DrawRectangleGradientV(posX, posY, width, height, *color1, *color2); }
void DrawRectangleGradientH_pointerized(int posX, int posY, int width, int height, Color* color1, Color* color2){ DrawRectangleGradientH(posX, posY, width, height, *color1, *color2); }
void DrawRectangleGradientEx_pointerized(Rectangle* rec, Color* col1, Color* col2, Color* col3, Color* col4){ DrawRectangleGradientEx(*rec, *col1, *col2, *col3, *col4); }
void DrawRectangleLines_pointerized(int posX, int posY, int width, int height, Color* color){ DrawRectangleLines(posX, posY, width, height, *color); }
void DrawRectangleLinesEx_pointerized(Rectangle* rec, float lineThick, Color* color){ DrawRectangleLinesEx(*rec, lineThick, *color); }
void DrawRectangleRounded_pointerized(Rectangle* rec, float roundness, int segments, Color* color){ DrawRectangleRounded(*rec, roundness, segments, *color); }
void DrawRectangleRoundedLines_pointerized(Rectangle* rec, float roundness, int segments, float lineThick, Color* color){ DrawRectangleRoundedLines(*rec, roundness, segments, lineThick, *color); }
void DrawTriangle_pointerized(Vector2* v1, Vector2* v2, Vector2* v3, Color* color){ DrawTriangle(*v1, *v2, *v3, *color); }
void DrawTriangleLines_pointerized(Vector2* v1, Vector2* v2, Vector2* v3, Color* color){ DrawTriangleLines(*v1, *v2, *v3, *color); }
void DrawTriangleFan_pointerized( Vector2 * points, int pointCount, Color* color){ DrawTriangleFan(points, pointCount, *color); }
void DrawTriangleStrip_pointerized( Vector2 * points, int pointCount, Color* color){ DrawTriangleStrip(points, pointCount, *color); }
void DrawPoly_pointerized(Vector2* center, int sides, float radius, float rotation, Color* color){ DrawPoly(*center, sides, radius, rotation, *color); }
void DrawPolyLines_pointerized(Vector2* center, int sides, float radius, float rotation, Color* color){ DrawPolyLines(*center, sides, radius, rotation, *color); }
void DrawPolyLinesEx_pointerized(Vector2* center, int sides, float radius, float rotation, float lineThick, Color* color){ DrawPolyLinesEx(*center, sides, radius, rotation, lineThick, *color); }
void DrawSplineLinear_pointerized( Vector2 * points, int pointCount, float thick, Color* color){ DrawSplineLinear(points, pointCount, thick, *color); }
void DrawSplineBasis_pointerized( Vector2 * points, int pointCount, float thick, Color* color){ DrawSplineBasis(points, pointCount, thick, *color); }
void DrawSplineCatmullRom_pointerized( Vector2 * points, int pointCount, float thick, Color* color){ DrawSplineCatmullRom(points, pointCount, thick, *color); }
void DrawSplineBezierQuadratic_pointerized( Vector2 * points, int pointCount, float thick, Color* color){ DrawSplineBezierQuadratic(points, pointCount, thick, *color); }
void DrawSplineBezierCubic_pointerized( Vector2 * points, int pointCount, float thick, Color* color){ DrawSplineBezierCubic(points, pointCount, thick, *color); }
void DrawSplineSegmentLinear_pointerized(Vector2* p1, Vector2* p2, float thick, Color* color){ DrawSplineSegmentLinear(*p1, *p2, thick, *color); }
void DrawSplineSegmentBasis_pointerized(Vector2* p1, Vector2* p2, Vector2* p3, Vector2* p4, float thick, Color* color){ DrawSplineSegmentBasis(*p1, *p2, *p3, *p4, thick, *color); }
void DrawSplineSegmentCatmullRom_pointerized(Vector2* p1, Vector2* p2, Vector2* p3, Vector2* p4, float thick, Color* color){ DrawSplineSegmentCatmullRom(*p1, *p2, *p3, *p4, thick, *color); }
void DrawSplineSegmentBezierQuadratic_pointerized(Vector2* p1, Vector2* c2, Vector2* p3, float thick, Color* color){ DrawSplineSegmentBezierQuadratic(*p1, *c2, *p3, thick, *color); }
void DrawSplineSegmentBezierCubic_pointerized(Vector2* p1, Vector2* c2, Vector2* c3, Vector2* p4, float thick, Color* color){ DrawSplineSegmentBezierCubic(*p1, *c2, *c3, *p4, thick, *color); }
Vector2* GetSplinePointLinear_pointerized(Vector2* startPos, Vector2* endPos, float t){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetSplinePointLinear(*startPos, *endPos, t); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetSplinePointBasis_pointerized(Vector2* p1, Vector2* p2, Vector2* p3, Vector2* p4, float t){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetSplinePointBasis(*p1, *p2, *p3, *p4, t); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetSplinePointCatmullRom_pointerized(Vector2* p1, Vector2* p2, Vector2* p3, Vector2* p4, float t){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetSplinePointCatmullRom(*p1, *p2, *p3, *p4, t); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetSplinePointBezierQuad_pointerized(Vector2* p1, Vector2* c2, Vector2* p3, float t){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetSplinePointBezierQuad(*p1, *c2, *p3, t); 
    *ptr = ret; 
    return ptr;
}
Vector2* GetSplinePointBezierCubic_pointerized(Vector2* p1, Vector2* c2, Vector2* c3, Vector2* p4, float t){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = GetSplinePointBezierCubic(*p1, *c2, *c3, *p4, t); 
    *ptr = ret; 
    return ptr;
}
bool CheckCollisionRecs_pointerized(Rectangle* rec1, Rectangle* rec2){ return CheckCollisionRecs(*rec1, *rec2); }
bool CheckCollisionCircles_pointerized(Vector2* center1, float radius1, Vector2* center2, float radius2){ return CheckCollisionCircles(*center1, radius1, *center2, radius2); }
bool CheckCollisionCircleRec_pointerized(Vector2* center, float radius, Rectangle* rec){ return CheckCollisionCircleRec(*center, radius, *rec); }
bool CheckCollisionPointRec_pointerized(Vector2* point, Rectangle* rec){ return CheckCollisionPointRec(*point, *rec); }
bool CheckCollisionPointCircle_pointerized(Vector2* point, Vector2* center, float radius){ return CheckCollisionPointCircle(*point, *center, radius); }
bool CheckCollisionPointTriangle_pointerized(Vector2* point, Vector2* p1, Vector2* p2, Vector2* p3){ return CheckCollisionPointTriangle(*point, *p1, *p2, *p3); }
bool CheckCollisionPointPoly_pointerized(Vector2* point,  Vector2 * points, int pointCount){ return CheckCollisionPointPoly(*point, points, pointCount); }
bool CheckCollisionLines_pointerized(Vector2* startPos1, Vector2* endPos1, Vector2* startPos2, Vector2* endPos2,  Vector2 * collisionPoint){ return CheckCollisionLines(*startPos1, *endPos1, *startPos2, *endPos2, collisionPoint); }
bool CheckCollisionPointLine_pointerized(Vector2* point, Vector2* p1, Vector2* p2, int threshold){ return CheckCollisionPointLine(*point, *p1, *p2, threshold); }
Rectangle* GetCollisionRec_pointerized(Rectangle* rec1, Rectangle* rec2){
    Rectangle* ptr = malloc(sizeof(Rectangle));
    Rectangle ret = GetCollisionRec(*rec1, *rec2); 
    *ptr = ret; 
    return ptr;
}
Image* LoadImage_pointerized( char * fileName){
    Image* ptr = malloc(sizeof(Image));
    Image ret = LoadImage(fileName); 
    *ptr = ret; 
    return ptr;
}
Image* LoadImageRaw_pointerized( char * fileName, int width, int height, int format, int headerSize){
    Image* ptr = malloc(sizeof(Image));
    Image ret = LoadImageRaw(fileName, width, height, format, headerSize); 
    *ptr = ret; 
    return ptr;
}
Image* LoadImageSvg_pointerized( char * fileNameOrString, int width, int height){
    Image* ptr = malloc(sizeof(Image));
    Image ret = LoadImageSvg(fileNameOrString, width, height); 
    *ptr = ret; 
    return ptr;
}
Image* LoadImageAnim_pointerized( char * fileName,  int * frames){
    Image* ptr = malloc(sizeof(Image));
    Image ret = LoadImageAnim(fileName, frames); 
    *ptr = ret; 
    return ptr;
}
Image* LoadImageFromMemory_pointerized( char * fileType,  char * fileData, int dataSize){
    Image* ptr = malloc(sizeof(Image));
    Image ret = LoadImageFromMemory(fileType, fileData, dataSize); 
    *ptr = ret; 
    return ptr;
}
Image* LoadImageFromTexture_pointerized(Texture2D* texture){
    Image* ptr = malloc(sizeof(Image));
    Image ret = LoadImageFromTexture(*texture); 
    *ptr = ret; 
    return ptr;
}
Image* LoadImageFromScreen_pointerized(){
    Image* ptr = malloc(sizeof(Image));
    Image ret = LoadImageFromScreen(); 
    *ptr = ret; 
    return ptr;
}
bool IsImageReady_pointerized(Image* image){ return IsImageReady(*image); }
void UnloadImage_pointerized(Image* image){ UnloadImage(*image); }
bool ExportImage_pointerized(Image* image,  char * fileName){ return ExportImage(*image, fileName); }
char* ExportImageToMemory_pointerized(Image* image,  char * fileType,  int * fileSize){ return ExportImageToMemory(*image, fileType, fileSize); }
bool ExportImageAsCode_pointerized(Image* image,  char * fileName){ return ExportImageAsCode(*image, fileName); }
Image* GenImageColor_pointerized(int width, int height, Color* color){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageColor(width, height, *color); 
    *ptr = ret; 
    return ptr;
}
Image* GenImageGradientLinear_pointerized(int width, int height, int direction, Color* start, Color* end){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageGradientLinear(width, height, direction, *start, *end); 
    *ptr = ret; 
    return ptr;
}
Image* GenImageGradientRadial_pointerized(int width, int height, float density, Color* inner, Color* outer){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageGradientRadial(width, height, density, *inner, *outer); 
    *ptr = ret; 
    return ptr;
}
Image* GenImageGradientSquare_pointerized(int width, int height, float density, Color* inner, Color* outer){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageGradientSquare(width, height, density, *inner, *outer); 
    *ptr = ret; 
    return ptr;
}
Image* GenImageChecked_pointerized(int width, int height, int checksX, int checksY, Color* col1, Color* col2){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageChecked(width, height, checksX, checksY, *col1, *col2); 
    *ptr = ret; 
    return ptr;
}
Image* GenImageWhiteNoise_pointerized(int width, int height, float factor){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageWhiteNoise(width, height, factor); 
    *ptr = ret; 
    return ptr;
}
Image* GenImagePerlinNoise_pointerized(int width, int height, int offsetX, int offsetY, float scale){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImagePerlinNoise(width, height, offsetX, offsetY, scale); 
    *ptr = ret; 
    return ptr;
}
Image* GenImageCellular_pointerized(int width, int height, int tileSize){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageCellular(width, height, tileSize); 
    *ptr = ret; 
    return ptr;
}
Image* GenImageText_pointerized(int width, int height,  char * text){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageText(width, height, text); 
    *ptr = ret; 
    return ptr;
}
Image* ImageCopy_pointerized(Image* image){
    Image* ptr = malloc(sizeof(Image));
    Image ret = ImageCopy(*image); 
    *ptr = ret; 
    return ptr;
}
Image* ImageFromImage_pointerized(Image* image, Rectangle* rec){
    Image* ptr = malloc(sizeof(Image));
    Image ret = ImageFromImage(*image, *rec); 
    *ptr = ret; 
    return ptr;
}
Image* ImageText_pointerized( char * text, int fontSize, Color* color){
    Image* ptr = malloc(sizeof(Image));
    Image ret = ImageText(text, fontSize, *color); 
    *ptr = ret; 
    return ptr;
}
Image* ImageTextEx_pointerized(Font* font,  char * text, float fontSize, float spacing, Color* tint){
    Image* ptr = malloc(sizeof(Image));
    Image ret = ImageTextEx(*font, text, fontSize, spacing, *tint); 
    *ptr = ret; 
    return ptr;
}
void ImageToPOT_pointerized( Image * image, Color* fill){ ImageToPOT(image, *fill); }
void ImageCrop_pointerized( Image * image, Rectangle* crop){ ImageCrop(image, *crop); }
void ImageAlphaClear_pointerized( Image * image, Color* color, float threshold){ ImageAlphaClear(image, *color, threshold); }
void ImageAlphaMask_pointerized( Image * image, Image* alphaMask){ ImageAlphaMask(image, *alphaMask); }
void ImageResizeCanvas_pointerized( Image * image, int newWidth, int newHeight, int offsetX, int offsetY, Color* fill){ ImageResizeCanvas(image, newWidth, newHeight, offsetX, offsetY, *fill); }
void ImageColorTint_pointerized( Image * image, Color* color){ ImageColorTint(image, *color); }
void ImageColorReplace_pointerized( Image * image, Color* color, Color* replace){ ImageColorReplace(image, *color, *replace); }
Color* LoadImageColors_pointerized(Image* image){ return LoadImageColors(*image); }
Color* LoadImagePalette_pointerized(Image* image, int maxPaletteSize,  int * colorCount){ return LoadImagePalette(*image, maxPaletteSize, colorCount); }
Rectangle* GetImageAlphaBorder_pointerized(Image* image, float threshold){
    Rectangle* ptr = malloc(sizeof(Rectangle));
    Rectangle ret = GetImageAlphaBorder(*image, threshold); 
    *ptr = ret; 
    return ptr;
}
Color* GetImageColor_pointerized(Image* image, int x, int y){
    Color* ptr = malloc(sizeof(Color));
    Color ret = GetImageColor(*image, x, y); 
    *ptr = ret; 
    return ptr;
}
void ImageClearBackground_pointerized( Image * dst, Color* color){ ImageClearBackground(dst, *color); }
void ImageDrawPixel_pointerized( Image * dst, int posX, int posY, Color* color){ ImageDrawPixel(dst, posX, posY, *color); }
void ImageDrawPixelV_pointerized( Image * dst, Vector2* position, Color* color){ ImageDrawPixelV(dst, *position, *color); }
void ImageDrawLine_pointerized( Image * dst, int startPosX, int startPosY, int endPosX, int endPosY, Color* color){ ImageDrawLine(dst, startPosX, startPosY, endPosX, endPosY, *color); }
void ImageDrawLineV_pointerized( Image * dst, Vector2* start, Vector2* end, Color* color){ ImageDrawLineV(dst, *start, *end, *color); }
void ImageDrawCircle_pointerized( Image * dst, int centerX, int centerY, int radius, Color* color){ ImageDrawCircle(dst, centerX, centerY, radius, *color); }
void ImageDrawCircleV_pointerized( Image * dst, Vector2* center, int radius, Color* color){ ImageDrawCircleV(dst, *center, radius, *color); }
void ImageDrawCircleLines_pointerized( Image * dst, int centerX, int centerY, int radius, Color* color){ ImageDrawCircleLines(dst, centerX, centerY, radius, *color); }
void ImageDrawCircleLinesV_pointerized( Image * dst, Vector2* center, int radius, Color* color){ ImageDrawCircleLinesV(dst, *center, radius, *color); }
void ImageDrawRectangle_pointerized( Image * dst, int posX, int posY, int width, int height, Color* color){ ImageDrawRectangle(dst, posX, posY, width, height, *color); }
void ImageDrawRectangleV_pointerized( Image * dst, Vector2* position, Vector2* size, Color* color){ ImageDrawRectangleV(dst, *position, *size, *color); }
void ImageDrawRectangleRec_pointerized( Image * dst, Rectangle* rec, Color* color){ ImageDrawRectangleRec(dst, *rec, *color); }
void ImageDrawRectangleLines_pointerized( Image * dst, Rectangle* rec, int thick, Color* color){ ImageDrawRectangleLines(dst, *rec, thick, *color); }
void ImageDraw_pointerized( Image * dst, Image* src, Rectangle* srcRec, Rectangle* dstRec, Color* tint){ ImageDraw(dst, *src, *srcRec, *dstRec, *tint); }
void ImageDrawText_pointerized( Image * dst,  char * text, int posX, int posY, int fontSize, Color* color){ ImageDrawText(dst, text, posX, posY, fontSize, *color); }
void ImageDrawTextEx_pointerized( Image * dst, Font* font,  char * text, Vector2* position, float fontSize, float spacing, Color* tint){ ImageDrawTextEx(dst, *font, text, *position, fontSize, spacing, *tint); }
Texture2D* LoadTexture_pointerized( char * fileName){
    Texture2D* ptr = malloc(sizeof(Texture2D));
    Texture2D ret = LoadTexture(fileName); 
    *ptr = ret; 
    return ptr;
}
Texture2D* LoadTextureFromImage_pointerized(Image* image){
    Texture2D* ptr = malloc(sizeof(Texture2D));
    Texture2D ret = LoadTextureFromImage(*image); 
    *ptr = ret; 
    return ptr;
}
TextureCubemap* LoadTextureCubemap_pointerized(Image* image, int layout){
    TextureCubemap* ptr = malloc(sizeof(TextureCubemap));
    TextureCubemap ret = LoadTextureCubemap(*image, layout); 
    *ptr = ret; 
    return ptr;
}
RenderTexture2D* LoadRenderTexture_pointerized(int width, int height){
    RenderTexture2D* ptr = malloc(sizeof(RenderTexture2D));
    RenderTexture2D ret = LoadRenderTexture(width, height); 
    *ptr = ret; 
    return ptr;
}
bool IsTextureReady_pointerized(Texture2D* texture){ return IsTextureReady(*texture); }
void UnloadTexture_pointerized(Texture2D* texture){ UnloadTexture(*texture); }
bool IsRenderTextureReady_pointerized(RenderTexture2D* target){ return IsRenderTextureReady(*target); }
void UnloadRenderTexture_pointerized(RenderTexture2D* target){ UnloadRenderTexture(*target); }
void UpdateTexture_pointerized(Texture2D* texture,  void * pixels){ UpdateTexture(*texture, pixels); }
void UpdateTextureRec_pointerized(Texture2D* texture, Rectangle* rec,  void * pixels){ UpdateTextureRec(*texture, *rec, pixels); }
void SetTextureFilter_pointerized(Texture2D* texture, int filter){ SetTextureFilter(*texture, filter); }
void SetTextureWrap_pointerized(Texture2D* texture, int wrap){ SetTextureWrap(*texture, wrap); }
void DrawTexture_pointerized(Texture2D* texture, int posX, int posY, Color* tint){ DrawTexture(*texture, posX, posY, *tint); }
void DrawTextureV_pointerized(Texture2D* texture, Vector2* position, Color* tint){ DrawTextureV(*texture, *position, *tint); }
void DrawTextureEx_pointerized(Texture2D* texture, Vector2* position, float rotation, float scale, Color* tint){ DrawTextureEx(*texture, *position, rotation, scale, *tint); }
void DrawTextureRec_pointerized(Texture2D* texture, Rectangle* source, Vector2* position, Color* tint){ DrawTextureRec(*texture, *source, *position, *tint); }
void DrawTexturePro_pointerized(Texture2D* texture, Rectangle* source, Rectangle* dest, Vector2* origin, float rotation, Color* tint){ DrawTexturePro(*texture, *source, *dest, *origin, rotation, *tint); }
void DrawTextureNPatch_pointerized(Texture2D* texture, NPatchInfo* nPatchInfo, Rectangle* dest, Vector2* origin, float rotation, Color* tint){ DrawTextureNPatch(*texture, *nPatchInfo, *dest, *origin, rotation, *tint); }
Color* Fade_pointerized(Color* color, float alpha){
    Color* ptr = malloc(sizeof(Color));
    Color ret = Fade(*color, alpha); 
    *ptr = ret; 
    return ptr;
}
int ColorToInt_pointerized(Color* color){ return ColorToInt(*color); }
Vector4* ColorNormalize_pointerized(Color* color){
    Vector4* ptr = malloc(sizeof(Vector4));
    Vector4 ret = ColorNormalize(*color); 
    *ptr = ret; 
    return ptr;
}
Color* ColorFromNormalized_pointerized(Vector4* normalized){
    Color* ptr = malloc(sizeof(Color));
    Color ret = ColorFromNormalized(*normalized); 
    *ptr = ret; 
    return ptr;
}
Vector3* ColorToHSV_pointerized(Color* color){
    Vector3* ptr = malloc(sizeof(Vector3));
    Vector3 ret = ColorToHSV(*color); 
    *ptr = ret; 
    return ptr;
}
Color* ColorFromHSV_pointerized(float hue, float saturation, float value){
    Color* ptr = malloc(sizeof(Color));
    Color ret = ColorFromHSV(hue, saturation, value); 
    *ptr = ret; 
    return ptr;
}
Color* ColorTint_pointerized(Color* color, Color* tint){
    Color* ptr = malloc(sizeof(Color));
    Color ret = ColorTint(*color, *tint); 
    *ptr = ret; 
    return ptr;
}
Color* ColorBrightness_pointerized(Color* color, float factor){
    Color* ptr = malloc(sizeof(Color));
    Color ret = ColorBrightness(*color, factor); 
    *ptr = ret; 
    return ptr;
}
Color* ColorContrast_pointerized(Color* color, float contrast){
    Color* ptr = malloc(sizeof(Color));
    Color ret = ColorContrast(*color, contrast); 
    *ptr = ret; 
    return ptr;
}
Color* ColorAlpha_pointerized(Color* color, float alpha){
    Color* ptr = malloc(sizeof(Color));
    Color ret = ColorAlpha(*color, alpha); 
    *ptr = ret; 
    return ptr;
}
Color* ColorAlphaBlend_pointerized(Color* dst, Color* src, Color* tint){
    Color* ptr = malloc(sizeof(Color));
    Color ret = ColorAlphaBlend(*dst, *src, *tint); 
    *ptr = ret; 
    return ptr;
}
Color* GetColor_pointerized(int hexValue){
    Color* ptr = malloc(sizeof(Color));
    Color ret = GetColor(hexValue); 
    *ptr = ret; 
    return ptr;
}
Color* GetPixelColor_pointerized( void * srcPtr, int format){
    Color* ptr = malloc(sizeof(Color));
    Color ret = GetPixelColor(srcPtr, format); 
    *ptr = ret; 
    return ptr;
}
void SetPixelColor_pointerized( void * dstPtr, Color* color, int format){ SetPixelColor(dstPtr, *color, format); }
Font* GetFontDefault_pointerized(){
    Font* ptr = malloc(sizeof(Font));
    Font ret = GetFontDefault(); 
    *ptr = ret; 
    return ptr;
}
Font* LoadFont_pointerized( char * fileName){
    Font* ptr = malloc(sizeof(Font));
    Font ret = LoadFont(fileName); 
    *ptr = ret; 
    return ptr;
}
Font* LoadFontEx_pointerized( char * fileName, int fontSize,  int * codepoints, int codepointCount){
    Font* ptr = malloc(sizeof(Font));
    Font ret = LoadFontEx(fileName, fontSize, codepoints, codepointCount); 
    *ptr = ret; 
    return ptr;
}
Font* LoadFontFromImage_pointerized(Image* image, Color* key, int firstChar){
    Font* ptr = malloc(sizeof(Font));
    Font ret = LoadFontFromImage(*image, *key, firstChar); 
    *ptr = ret; 
    return ptr;
}
Font* LoadFontFromMemory_pointerized( char * fileType,  char * fileData, int dataSize, int fontSize,  int * codepoints, int codepointCount){
    Font* ptr = malloc(sizeof(Font));
    Font ret = LoadFontFromMemory(fileType, fileData, dataSize, fontSize, codepoints, codepointCount); 
    *ptr = ret; 
    return ptr;
}
bool IsFontReady_pointerized(Font* font){ return IsFontReady(*font); }
Image* GenImageFontAtlas_pointerized( GlyphInfo * glyphs,  Rectangle * * glyphRecs, int glyphCount, int fontSize, int padding, int packMethod){
    Image* ptr = malloc(sizeof(Image));
    Image ret = GenImageFontAtlas(glyphs, glyphRecs, glyphCount, fontSize, padding, packMethod); 
    *ptr = ret; 
    return ptr;
}
void UnloadFont_pointerized(Font* font){ UnloadFont(*font); }
bool ExportFontAsCode_pointerized(Font* font,  char * fileName){ return ExportFontAsCode(*font, fileName); }
void DrawText_pointerized( char * text, int posX, int posY, int fontSize, Color* color){ DrawText(text, posX, posY, fontSize, *color); }
void DrawTextEx_pointerized(Font* font,  char * text, Vector2* position, float fontSize, float spacing, Color* tint){ DrawTextEx(*font, text, *position, fontSize, spacing, *tint); }
void DrawTextPro_pointerized(Font* font,  char * text, Vector2* position, Vector2* origin, float rotation, float fontSize, float spacing, Color* tint){ DrawTextPro(*font, text, *position, *origin, rotation, fontSize, spacing, *tint); }
void DrawTextCodepoint_pointerized(Font* font, int codepoint, Vector2* position, float fontSize, Color* tint){ DrawTextCodepoint(*font, codepoint, *position, fontSize, *tint); }
void DrawTextCodepoints_pointerized(Font* font,  int * codepoints, int codepointCount, Vector2* position, float fontSize, float spacing, Color* tint){ DrawTextCodepoints(*font, codepoints, codepointCount, *position, fontSize, spacing, *tint); }
Vector2* MeasureTextEx_pointerized(Font* font,  char * text, float fontSize, float spacing){
    Vector2* ptr = malloc(sizeof(Vector2));
    Vector2 ret = MeasureTextEx(*font, text, fontSize, spacing); 
    *ptr = ret; 
    return ptr;
}
int GetGlyphIndex_pointerized(Font* font, int codepoint){ return GetGlyphIndex(*font, codepoint); }
GlyphInfo* GetGlyphInfo_pointerized(Font* font, int codepoint){
    GlyphInfo* ptr = malloc(sizeof(GlyphInfo));
    GlyphInfo ret = GetGlyphInfo(*font, codepoint); 
    *ptr = ret; 
    return ptr;
}
Rectangle* GetGlyphAtlasRec_pointerized(Font* font, int codepoint){
    Rectangle* ptr = malloc(sizeof(Rectangle));
    Rectangle ret = GetGlyphAtlasRec(*font, codepoint); 
    *ptr = ret; 
    return ptr;
}
void DrawLine3D_pointerized(Vector3* startPos, Vector3* endPos, Color* color){ DrawLine3D(*startPos, *endPos, *color); }
void DrawPoint3D_pointerized(Vector3* position, Color* color){ DrawPoint3D(*position, *color); }
void DrawCircle3D_pointerized(Vector3* center, float radius, Vector3* rotationAxis, float rotationAngle, Color* color){ DrawCircle3D(*center, radius, *rotationAxis, rotationAngle, *color); }
void DrawTriangle3D_pointerized(Vector3* v1, Vector3* v2, Vector3* v3, Color* color){ DrawTriangle3D(*v1, *v2, *v3, *color); }
void DrawTriangleStrip3D_pointerized( Vector3 * points, int pointCount, Color* color){ DrawTriangleStrip3D(points, pointCount, *color); }
void DrawCube_pointerized(Vector3* position, float width, float height, float length, Color* color){ DrawCube(*position, width, height, length, *color); }
void DrawCubeV_pointerized(Vector3* position, Vector3* size, Color* color){ DrawCubeV(*position, *size, *color); }
void DrawCubeWires_pointerized(Vector3* position, float width, float height, float length, Color* color){ DrawCubeWires(*position, width, height, length, *color); }
void DrawCubeWiresV_pointerized(Vector3* position, Vector3* size, Color* color){ DrawCubeWiresV(*position, *size, *color); }
void DrawSphere_pointerized(Vector3* centerPos, float radius, Color* color){ DrawSphere(*centerPos, radius, *color); }
void DrawSphereEx_pointerized(Vector3* centerPos, float radius, int rings, int slices, Color* color){ DrawSphereEx(*centerPos, radius, rings, slices, *color); }
void DrawSphereWires_pointerized(Vector3* centerPos, float radius, int rings, int slices, Color* color){ DrawSphereWires(*centerPos, radius, rings, slices, *color); }
void DrawCylinder_pointerized(Vector3* position, float radiusTop, float radiusBottom, float height, int slices, Color* color){ DrawCylinder(*position, radiusTop, radiusBottom, height, slices, *color); }
void DrawCylinderEx_pointerized(Vector3* startPos, Vector3* endPos, float startRadius, float endRadius, int sides, Color* color){ DrawCylinderEx(*startPos, *endPos, startRadius, endRadius, sides, *color); }
void DrawCylinderWires_pointerized(Vector3* position, float radiusTop, float radiusBottom, float height, int slices, Color* color){ DrawCylinderWires(*position, radiusTop, radiusBottom, height, slices, *color); }
void DrawCylinderWiresEx_pointerized(Vector3* startPos, Vector3* endPos, float startRadius, float endRadius, int sides, Color* color){ DrawCylinderWiresEx(*startPos, *endPos, startRadius, endRadius, sides, *color); }
void DrawCapsule_pointerized(Vector3* startPos, Vector3* endPos, float radius, int slices, int rings, Color* color){ DrawCapsule(*startPos, *endPos, radius, slices, rings, *color); }
void DrawCapsuleWires_pointerized(Vector3* startPos, Vector3* endPos, float radius, int slices, int rings, Color* color){ DrawCapsuleWires(*startPos, *endPos, radius, slices, rings, *color); }
void DrawPlane_pointerized(Vector3* centerPos, Vector2* size, Color* color){ DrawPlane(*centerPos, *size, *color); }
void DrawRay_pointerized(Ray* ray, Color* color){ DrawRay(*ray, *color); }
Model* LoadModel_pointerized( char * fileName){
    Model* ptr = malloc(sizeof(Model));
    Model ret = LoadModel(fileName); 
    *ptr = ret; 
    return ptr;
}
Model* LoadModelFromMesh_pointerized(Mesh* mesh){
    Model* ptr = malloc(sizeof(Model));
    Model ret = LoadModelFromMesh(*mesh); 
    *ptr = ret; 
    return ptr;
}
bool IsModelReady_pointerized(Model* model){ return IsModelReady(*model); }
void UnloadModel_pointerized(Model* model){ UnloadModel(*model); }
BoundingBox* GetModelBoundingBox_pointerized(Model* model){
    BoundingBox* ptr = malloc(sizeof(BoundingBox));
    BoundingBox ret = GetModelBoundingBox(*model); 
    *ptr = ret; 
    return ptr;
}
void DrawModel_pointerized(Model* model, Vector3* position, float scale, Color* tint){ DrawModel(*model, *position, scale, *tint); }
void DrawModelEx_pointerized(Model* model, Vector3* position, Vector3* rotationAxis, float rotationAngle, Vector3* scale, Color* tint){ DrawModelEx(*model, *position, *rotationAxis, rotationAngle, *scale, *tint); }
void DrawModelWires_pointerized(Model* model, Vector3* position, float scale, Color* tint){ DrawModelWires(*model, *position, scale, *tint); }
void DrawModelWiresEx_pointerized(Model* model, Vector3* position, Vector3* rotationAxis, float rotationAngle, Vector3* scale, Color* tint){ DrawModelWiresEx(*model, *position, *rotationAxis, rotationAngle, *scale, *tint); }
void DrawBoundingBox_pointerized(BoundingBox* box, Color* color){ DrawBoundingBox(*box, *color); }
void DrawBillboard_pointerized(Camera* camera, Texture2D* texture, Vector3* position, float size, Color* tint){ DrawBillboard(*camera, *texture, *position, size, *tint); }
void DrawBillboardRec_pointerized(Camera* camera, Texture2D* texture, Rectangle* source, Vector3* position, Vector2* size, Color* tint){ DrawBillboardRec(*camera, *texture, *source, *position, *size, *tint); }
void DrawBillboardPro_pointerized(Camera* camera, Texture2D* texture, Rectangle* source, Vector3* position, Vector3* up, Vector2* size, Vector2* origin, float rotation, Color* tint){ DrawBillboardPro(*camera, *texture, *source, *position, *up, *size, *origin, rotation, *tint); }
void UpdateMeshBuffer_pointerized(Mesh* mesh, int index,  void * data, int dataSize, int offset){ UpdateMeshBuffer(*mesh, index, data, dataSize, offset); }
void UnloadMesh_pointerized(Mesh* mesh){ UnloadMesh(*mesh); }
void DrawMesh_pointerized(Mesh* mesh, Material* material, Matrix* transform){ DrawMesh(*mesh, *material, *transform); }
void DrawMeshInstanced_pointerized(Mesh* mesh, Material* material,  Matrix * transforms, int instances){ DrawMeshInstanced(*mesh, *material, transforms, instances); }
BoundingBox* GetMeshBoundingBox_pointerized(Mesh* mesh){
    BoundingBox* ptr = malloc(sizeof(BoundingBox));
    BoundingBox ret = GetMeshBoundingBox(*mesh); 
    *ptr = ret; 
    return ptr;
}
bool ExportMesh_pointerized(Mesh* mesh,  char * fileName){ return ExportMesh(*mesh, fileName); }
bool ExportMeshAsCode_pointerized(Mesh* mesh,  char * fileName){ return ExportMeshAsCode(*mesh, fileName); }
Mesh* GenMeshPoly_pointerized(int sides, float radius){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshPoly(sides, radius); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshPlane_pointerized(float width, float length, int resX, int resZ){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshPlane(width, length, resX, resZ); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshCube_pointerized(float width, float height, float length){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshCube(width, height, length); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshSphere_pointerized(float radius, int rings, int slices){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshSphere(radius, rings, slices); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshHemiSphere_pointerized(float radius, int rings, int slices){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshHemiSphere(radius, rings, slices); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshCylinder_pointerized(float radius, float height, int slices){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshCylinder(radius, height, slices); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshCone_pointerized(float radius, float height, int slices){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshCone(radius, height, slices); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshTorus_pointerized(float radius, float size, int radSeg, int sides){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshTorus(radius, size, radSeg, sides); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshKnot_pointerized(float radius, float size, int radSeg, int sides){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshKnot(radius, size, radSeg, sides); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshHeightmap_pointerized(Image* heightmap, Vector3* size){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshHeightmap(*heightmap, *size); 
    *ptr = ret; 
    return ptr;
}
Mesh* GenMeshCubicmap_pointerized(Image* cubicmap, Vector3* cubeSize){
    Mesh* ptr = malloc(sizeof(Mesh));
    Mesh ret = GenMeshCubicmap(*cubicmap, *cubeSize); 
    *ptr = ret; 
    return ptr;
}
Material* LoadMaterialDefault_pointerized(){
    Material* ptr = malloc(sizeof(Material));
    Material ret = LoadMaterialDefault(); 
    *ptr = ret; 
    return ptr;
}
bool IsMaterialReady_pointerized(Material* material){ return IsMaterialReady(*material); }
void UnloadMaterial_pointerized(Material* material){ UnloadMaterial(*material); }
void SetMaterialTexture_pointerized( Material * material, int mapType, Texture2D* texture){ SetMaterialTexture(material, mapType, *texture); }
void UpdateModelAnimation_pointerized(Model* model, ModelAnimation* anim, int frame){ UpdateModelAnimation(*model, *anim, frame); }
void UnloadModelAnimation_pointerized(ModelAnimation* anim){ UnloadModelAnimation(*anim); }
bool IsModelAnimationValid_pointerized(Model* model, ModelAnimation* anim){ return IsModelAnimationValid(*model, *anim); }
bool CheckCollisionSpheres_pointerized(Vector3* center1, float radius1, Vector3* center2, float radius2){ return CheckCollisionSpheres(*center1, radius1, *center2, radius2); }
bool CheckCollisionBoxes_pointerized(BoundingBox* box1, BoundingBox* box2){ return CheckCollisionBoxes(*box1, *box2); }
bool CheckCollisionBoxSphere_pointerized(BoundingBox* box, Vector3* center, float radius){ return CheckCollisionBoxSphere(*box, *center, radius); }
RayCollision* GetRayCollisionSphere_pointerized(Ray* ray, Vector3* center, float radius){
    RayCollision* ptr = malloc(sizeof(RayCollision));
    RayCollision ret = GetRayCollisionSphere(*ray, *center, radius); 
    *ptr = ret; 
    return ptr;
}
RayCollision* GetRayCollisionBox_pointerized(Ray* ray, BoundingBox* box){
    RayCollision* ptr = malloc(sizeof(RayCollision));
    RayCollision ret = GetRayCollisionBox(*ray, *box); 
    *ptr = ret; 
    return ptr;
}
RayCollision* GetRayCollisionMesh_pointerized(Ray* ray, Mesh* mesh, Matrix* transform){
    RayCollision* ptr = malloc(sizeof(RayCollision));
    RayCollision ret = GetRayCollisionMesh(*ray, *mesh, *transform); 
    *ptr = ret; 
    return ptr;
}
RayCollision* GetRayCollisionTriangle_pointerized(Ray* ray, Vector3* p1, Vector3* p2, Vector3* p3){
    RayCollision* ptr = malloc(sizeof(RayCollision));
    RayCollision ret = GetRayCollisionTriangle(*ray, *p1, *p2, *p3); 
    *ptr = ret; 
    return ptr;
}
RayCollision* GetRayCollisionQuad_pointerized(Ray* ray, Vector3* p1, Vector3* p2, Vector3* p3, Vector3* p4){
    RayCollision* ptr = malloc(sizeof(RayCollision));
    RayCollision ret = GetRayCollisionQuad(*ray, *p1, *p2, *p3, *p4); 
    *ptr = ret; 
    return ptr;
}
Wave* LoadWave_pointerized( char * fileName){
    Wave* ptr = malloc(sizeof(Wave));
    Wave ret = LoadWave(fileName); 
    *ptr = ret; 
    return ptr;
}
Wave* LoadWaveFromMemory_pointerized( char * fileType,  char * fileData, int dataSize){
    Wave* ptr = malloc(sizeof(Wave));
    Wave ret = LoadWaveFromMemory(fileType, fileData, dataSize); 
    *ptr = ret; 
    return ptr;
}
bool IsWaveReady_pointerized(Wave* wave){ return IsWaveReady(*wave); }
Sound* LoadSound_pointerized( char * fileName){
    Sound* ptr = malloc(sizeof(Sound));
    Sound ret = LoadSound(fileName); 
    *ptr = ret; 
    return ptr;
}
Sound* LoadSoundFromWave_pointerized(Wave* wave){
    Sound* ptr = malloc(sizeof(Sound));
    Sound ret = LoadSoundFromWave(*wave); 
    *ptr = ret; 
    return ptr;
}
Sound* LoadSoundAlias_pointerized(Sound* source){
    Sound* ptr = malloc(sizeof(Sound));
    Sound ret = LoadSoundAlias(*source); 
    *ptr = ret; 
    return ptr;
}
bool IsSoundReady_pointerized(Sound* sound){ return IsSoundReady(*sound); }
void UpdateSound_pointerized(Sound* sound,  void * data, int sampleCount){ UpdateSound(*sound, data, sampleCount); }
void UnloadWave_pointerized(Wave* wave){ UnloadWave(*wave); }
void UnloadSound_pointerized(Sound* sound){ UnloadSound(*sound); }
void UnloadSoundAlias_pointerized(Sound* alias){ UnloadSoundAlias(*alias); }
bool ExportWave_pointerized(Wave* wave,  char * fileName){ return ExportWave(*wave, fileName); }
bool ExportWaveAsCode_pointerized(Wave* wave,  char * fileName){ return ExportWaveAsCode(*wave, fileName); }
void PlaySound_pointerized(Sound* sound){ PlaySound(*sound); }
void StopSound_pointerized(Sound* sound){ StopSound(*sound); }
void PauseSound_pointerized(Sound* sound){ PauseSound(*sound); }
void ResumeSound_pointerized(Sound* sound){ ResumeSound(*sound); }
bool IsSoundPlaying_pointerized(Sound* sound){ return IsSoundPlaying(*sound); }
void SetSoundVolume_pointerized(Sound* sound, float volume){ SetSoundVolume(*sound, volume); }
void SetSoundPitch_pointerized(Sound* sound, float pitch){ SetSoundPitch(*sound, pitch); }
void SetSoundPan_pointerized(Sound* sound, float pan){ SetSoundPan(*sound, pan); }
Wave* WaveCopy_pointerized(Wave* wave){
    Wave* ptr = malloc(sizeof(Wave));
    Wave ret = WaveCopy(*wave); 
    *ptr = ret; 
    return ptr;
}
float* LoadWaveSamples_pointerized(Wave* wave){ return LoadWaveSamples(*wave); }
Music* LoadMusicStream_pointerized( char * fileName){
    Music* ptr = malloc(sizeof(Music));
    Music ret = LoadMusicStream(fileName); 
    *ptr = ret; 
    return ptr;
}
Music* LoadMusicStreamFromMemory_pointerized( char * fileType,  char * data, int dataSize){
    Music* ptr = malloc(sizeof(Music));
    Music ret = LoadMusicStreamFromMemory(fileType, data, dataSize); 
    *ptr = ret; 
    return ptr;
}
bool IsMusicReady_pointerized(Music* music){ return IsMusicReady(*music); }
void UnloadMusicStream_pointerized(Music* music){ UnloadMusicStream(*music); }
void PlayMusicStream_pointerized(Music* music){ PlayMusicStream(*music); }
bool IsMusicStreamPlaying_pointerized(Music* music){ return IsMusicStreamPlaying(*music); }
void UpdateMusicStream_pointerized(Music* music){ UpdateMusicStream(*music); }
void StopMusicStream_pointerized(Music* music){ StopMusicStream(*music); }
void PauseMusicStream_pointerized(Music* music){ PauseMusicStream(*music); }
void ResumeMusicStream_pointerized(Music* music){ ResumeMusicStream(*music); }
void SeekMusicStream_pointerized(Music* music, float position){ SeekMusicStream(*music, position); }
void SetMusicVolume_pointerized(Music* music, float volume){ SetMusicVolume(*music, volume); }
void SetMusicPitch_pointerized(Music* music, float pitch){ SetMusicPitch(*music, pitch); }
void SetMusicPan_pointerized(Music* music, float pan){ SetMusicPan(*music, pan); }
float GetMusicTimeLength_pointerized(Music* music){ return GetMusicTimeLength(*music); }
float GetMusicTimePlayed_pointerized(Music* music){ return GetMusicTimePlayed(*music); }
AudioStream* LoadAudioStream_pointerized(int sampleRate, int sampleSize, int channels){
    AudioStream* ptr = malloc(sizeof(AudioStream));
    AudioStream ret = LoadAudioStream(sampleRate, sampleSize, channels); 
    *ptr = ret; 
    return ptr;
}
bool IsAudioStreamReady_pointerized(AudioStream* stream){ return IsAudioStreamReady(*stream); }
void UnloadAudioStream_pointerized(AudioStream* stream){ UnloadAudioStream(*stream); }
void UpdateAudioStream_pointerized(AudioStream* stream,  void * data, int frameCount){ UpdateAudioStream(*stream, data, frameCount); }
bool IsAudioStreamProcessed_pointerized(AudioStream* stream){ return IsAudioStreamProcessed(*stream); }
void PlayAudioStream_pointerized(AudioStream* stream){ PlayAudioStream(*stream); }
void PauseAudioStream_pointerized(AudioStream* stream){ PauseAudioStream(*stream); }
void ResumeAudioStream_pointerized(AudioStream* stream){ ResumeAudioStream(*stream); }
bool IsAudioStreamPlaying_pointerized(AudioStream* stream){ return IsAudioStreamPlaying(*stream); }
void StopAudioStream_pointerized(AudioStream* stream){ StopAudioStream(*stream); }
void SetAudioStreamVolume_pointerized(AudioStream* stream, float volume){ SetAudioStreamVolume(*stream, volume); }
void SetAudioStreamPitch_pointerized(AudioStream* stream, float pitch){ SetAudioStreamPitch(*stream, pitch); }
void SetAudioStreamPan_pointerized(AudioStream* stream, float pan){ SetAudioStreamPan(*stream, pan); }
void SetAudioStreamCallback_pointerized(AudioStream* stream, AudioCallback callback){ SetAudioStreamCallback(*stream, callback); }
void AttachAudioStreamProcessor_pointerized(AudioStream* stream, AudioCallback processor){ AttachAudioStreamProcessor(*stream, processor); }
void DetachAudioStreamProcessor_pointerized(AudioStream* stream, AudioCallback processor){ DetachAudioStreamProcessor(*stream, processor); }
